import React, { useState, useEffect } from "react";
import { Chess } from "chess.js";
import { 
  Volume2, VolumeX, Mic, MicOff, Send, Cpu, Sparkles, AlertCircle, RefreshCw 
} from "lucide-react";
import { UserProfile } from "../types";
import { Chessboard } from "./Chessboard";

interface VoiceCoachProps {
  profile: UserProfile;
}

interface ChatMessage {
  sender: "user" | "coach";
  text: string;
}

export const VoiceCoach: React.FC<VoiceCoachProps> = ({ profile }) => {
  const [boardGame, setBoardGame] = useState<Chess>(new Chess());
  const [arrows, setArrows] = useState<string[]>([]);
  const [highlights, setHighlights] = useState<string[]>([]);
  
  const [isListening, setIsListening] = useState(false);
  const [soundEnabled, setSoundEnabled] = useState(true);
  const [userInput, setUserInput] = useState("");
  const [chatHistory, setChatHistory] = useState<ChatMessage[]>([
    { sender: "coach", text: "Hello! I am your AI Grandmaster Coach. You can type any strategic question here, or click the Mic to speak. Ask me things like: 'What's the best strategic plan here?' or 'How do I attack the king?'." }
  ]);
  const [loading, setLoading] = useState(false);

  const popularQuestions = [
    "What's the best plan here?",
    "Why is my king vulnerable?",
    "How do I attack the center?",
    "Explain the threat in this position."
  ];

  const handleSendMessage = async (textToSend: string) => {
    if (!textToSend.trim()) return;

    // Add user message
    const userMsg: ChatMessage = { sender: "user", text: textToSend };
    const updatedHistory: ChatMessage[] = [...chatHistory, userMsg];
    setChatHistory(updatedHistory);
    setUserInput("");
    setLoading(true);

    try {
      const response = await fetch("/api/coach/voice", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          question: textToSend,
          fen: boardGame.fen(),
          history: boardGame.history(),
          rating: profile.elo
        })
      });

      const data = await response.json();
      if (data.spokenResponse) {
        const coachMsg: ChatMessage = { sender: "coach", text: data.spokenResponse };
        setChatHistory([...updatedHistory, coachMsg]);
        
        // Draw arrows & highlights generated by Gemini
        if (data.arrows) setArrows(data.arrows);
        if (data.highlights) setHighlights(data.highlights);

        // Vocalize response
        if (soundEnabled && window.speechSynthesis) {
          // Stop current speaking
          window.speechSynthesis.cancel();
          const utterance = new SpeechSynthesisUtterance(data.spokenResponse);
          window.speechSynthesis.speak(utterance);
        }
      } else {
        throw new Error("Invalid response format");
      }
    } catch (e) {
      console.error(e);
      // Fallback
      const fallbackMsg = "Developing your central minor pieces and preparing a rook lift is standard practice in this structure. Always ensure your kingside squares are secured before attacking.";
      const fallbackCoachMsg: ChatMessage = { sender: "coach", text: fallbackMsg };
      setChatHistory([...updatedHistory, fallbackCoachMsg]);
      
      if (soundEnabled && window.speechSynthesis) {
        window.speechSynthesis.speak(new SpeechSynthesisUtterance(fallbackMsg));
      }
    } finally {
      setLoading(false);
    }
  };

  const startVoiceRecordingSimulation = () => {
    setIsListening(true);
    // Simulate speech-to-text with random prompt after 3s
    setTimeout(() => {
      setIsListening(false);
      const sampleQueries = [
        "What is the best attacking plan in this structure?",
        "How do I safeguard my king on the queenside?",
        "Explain how to establish a strong knight outpost here.",
        "What threats should I protect against on the f7 square?"
      ];
      const randomQuery = sampleQueries[Math.floor(Math.random() * sampleQueries.length)];
      handleSendMessage(randomQuery);
    }, 3000);
  };

  const handleResetBoard = () => {
    setBoardGame(new Chess());
    setArrows([]);
    setHighlights([]);
  };

  return (
    <div className="space-y-6 font-sans">
      {/* Header */}
      <div className="flex justify-between items-center pb-3 border-b border-amber-500/15">
        <div>
          <h1 className="text-3xl font-extrabold font-serif tracking-tight text-white flex items-center gap-2">
            <span className="bg-gradient-to-r from-amber-300 via-yellow-400 to-amber-500 bg-clip-text text-transparent">Voice AI Chess Coach</span>
          </h1>
          <p className="text-sm text-slate-400 mt-1">
            Communicate naturally with ChessZen AI. The Coach will answer vocally while drawing lines & highlights on the board!
          </p>
        </div>
        <button
          onClick={() => setSoundEnabled(!soundEnabled)}
          className={`p-2.5 rounded-xl border cursor-pointer transition-all ${
            soundEnabled 
              ? "bg-amber-500/15 border-amber-500/40 text-amber-300 shadow-md shadow-amber-500/10" 
              : "bg-[#151922] border-amber-500/20 text-slate-400 hover:text-white"
          }`}
          title={soundEnabled ? "Disable Voice Output" : "Enable Voice Output"}
        >
          {soundEnabled ? <Volume2 className="h-4 w-4 animate-pulse text-amber-400" /> : <VolumeX className="h-4 w-4 text-slate-400" />}
        </button>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
        {/* Left Board Column */}
        <div className="lg:col-span-5 space-y-4">
          <div className="glass-card p-6 rounded-2xl shadow-xl flex flex-col items-center">
            <Chessboard
              game={boardGame}
              onMove={(from, to, promo) => {
                boardGame.move({ from, to, promotion: promo || "q" });
                setBoardGame(new Chess(boardGame.fen()));
              }}
              arrows={arrows}
              highlights={highlights}
              interactive={true}
              theme={profile.themePreference || profile.boardTheme}
            />
          </div>

          <div className="flex justify-between items-center text-xs font-semibold text-slate-400 font-mono">
            <button
              onClick={handleResetBoard}
              className="px-3.5 py-1.5 border border-amber-500/30 rounded-xl hover:bg-amber-500/10 bg-[#151922] text-amber-200 cursor-pointer text-xs font-bold shadow-sm transition-all"
            >
              Reset Coach Board
            </button>
            <span className="text-amber-200/60">Play moves on board to query AI</span>
          </div>

          {/* Quick-select prompts */}
          <div className="space-y-2">
            <h4 className="text-[10px] font-bold text-amber-300/80 uppercase tracking-wider font-mono">Suggested Questions</h4>
            <div className="grid grid-cols-2 gap-2">
              {popularQuestions.map((q) => (
                <button
                  key={q}
                  onClick={() => handleSendMessage(q)}
                  disabled={loading}
                  className="p-3 border border-amber-500/20 hover:border-amber-400 bg-[#151922]/80 hover:bg-amber-500/10 rounded-xl text-left text-xs font-bold text-amber-100 transition-all cursor-pointer truncate shadow-sm"
                >
                  {q}
                </button>
              ))}
            </div>
          </div>
        </div>

        {/* Right Chat panel */}
        <div className="lg:col-span-7 flex flex-col h-[520px] rounded-2xl border border-slate-200/60 bg-white shadow-sm dark:bg-[#0b111e]/60 dark:backdrop-blur-md dark:border-slate-800 overflow-hidden">
          
          {/* Active Coach Indicator */}
          <div className="p-4 bg-slate-50 dark:bg-slate-950 border-b border-slate-100 dark:border-slate-800 flex items-center justify-between">
            <div className="flex items-center gap-2.5">
              <div className="h-2.5 w-2.5 bg-emerald-500 rounded-full animate-ping" />
              <div className="text-xs font-bold text-slate-700 dark:text-slate-300 font-mono flex items-center gap-1.5">
                <Cpu className="h-3.5 w-3.5 text-indigo-500" /> CHESSZEN COACH AUDIO
              </div>
            </div>
          </div>

          {/* Message log */}
          <div className="flex-1 p-4 overflow-y-auto space-y-4">
            {chatHistory.map((chat, idx) => {
              const isCoach = chat.sender === "coach";
              return (
                <div key={idx} className={`flex ${isCoach ? "justify-start" : "justify-end"}`}>
                  <div className={`p-4 rounded-2xl text-xs max-w-[85%] leading-relaxed ${
                    isCoach
                      ? "bg-slate-50 text-slate-800 dark:bg-slate-950 dark:text-slate-200 rounded-tl-none border border-slate-200/40 dark:border-slate-800/60"
                      : "bg-gradient-to-r from-emerald-500 to-indigo-600 text-white rounded-tr-none shadow-md font-medium"
                  }`}>
                    {isCoach && (
                      <div className="flex items-center gap-1 text-[9px] font-bold uppercase font-mono text-indigo-500 dark:text-emerald-400 mb-1">
                        <Sparkles className="h-3 w-3 fill-current animate-pulse" /> Grandmaster AI Coach
                      </div>
                    )}
                    <p className="whitespace-pre-line leading-relaxed">{chat.text}</p>
                  </div>
                </div>
              );
            })}

            {loading && (
              <div className="flex justify-start">
                <div className="bg-slate-50 dark:bg-slate-950 border border-slate-200/40 p-4 rounded-2xl rounded-tl-none flex items-center gap-2">
                  <RefreshCw className="h-4 w-4 text-emerald-500 animate-spin" />
                  <span className="text-xs font-bold text-slate-400 font-mono">AI Coach is thinking...</span>
                </div>
              </div>
            )}
          </div>

          {/* Form input */}
          <div className="p-3 border-t border-slate-100 dark:border-slate-800 flex items-center gap-2 bg-slate-50/50 dark:bg-slate-950/30">
            <button
              onClick={startVoiceRecordingSimulation}
              disabled={isListening || loading}
              className={`p-3 rounded-xl border flex items-center justify-center transition-all cursor-pointer ${
                isListening 
                  ? "bg-red-500 border-red-600 text-white animate-pulse" 
                  : "bg-white border-slate-200 text-slate-600 hover:bg-slate-50 dark:bg-slate-900"
              }`}
            >
              {isListening ? <Mic className="h-4 w-4" /> : <MicOff className="h-4 w-4 text-slate-400" />}
            </button>

            <input
              type="text"
              value={userInput}
              onChange={(e) => setUserInput(e.target.value)}
              placeholder={isListening ? "Listening... Speak now!" : "Type a chess question (e.g. 'How do I attack f7?')..."}
              disabled={isListening || loading}
              onKeyDown={(e) => e.key === "Enter" && handleSendMessage(userInput)}
              className="flex-1 rounded-xl border border-slate-200 p-3 text-xs bg-white dark:bg-[#0b111e]/40 dark:border-slate-800 focus:outline-none focus:ring-emerald-500 focus:border-emerald-500 dark:text-white"
            />

            <button
              onClick={() => handleSendMessage(userInput)}
              disabled={!userInput.trim() || loading}
              className="p-3 bg-gradient-to-r from-emerald-500 to-indigo-600 text-white rounded-xl font-bold hover:opacity-90 active:scale-95 transition-all cursor-pointer disabled:opacity-50 flex items-center justify-center shadow-md shadow-emerald-500/10"
            >
              <Send className="h-4 w-4" />
            </button>
          </div>

        </div>
      </div>
    </div>
  );
};
